Neos:
  Neos:
    fusion:
      autoInclude:
        UpAssist.Neos.RSSFeed: true
    userInterface:
      translation:
        autoInclude:
          UpAssist.Neos.RSSFeed:
            - 'NodeTypes/*'
